### ISSUE TITLE
Issues with the about sections on iOS mobile

### ISSUE THREAD

**Issue by gbaman** [rpct/rpct.github.io#2]
The about sections for each CT do not work on mobile on iOS. Am assuming may be similar on Android.
If need be, have it take the user to a separate page for each person.

**Comment by miltonio94** [comment]
Heeey Andrew, this has been fixed... the mobile platforms weren't recognising the links as links for some reason so I changed it to buttons instead

**Comment by gbaman** [comment]
Cool, can confirm this is fixed.
